services:
  - type: static
    name: whatsapp-frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend-panel

  - type: web
    name: whatsapp-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: backend/full
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: BOT_NAME
        value: "Melodia WhatsApp Bot"
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-db
          property: connectionString

databases:
  - name: whatsapp-db
    plan: free



