services:
  - type: web
    name: whatsapp-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node full/index.js
    rootDir: backend  # <--- ¡ESTO ES LO IMPORTANTE!
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: BOT_NAME
        value: "Melodia WhatsApp Bot"
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-db
          property: connectionString
      - key: DB_POOL_MIN
        value: 2
      - key: DB_POOL_MAX
        value: 10
      - key: DB_ACQUIRE_TIMEOUT
        value: 60000
      - key: DB_IDLE_TIMEOUT
        value: 30000

databases:
  - name: whatsapp-db
    plan: free

